name: Deploy Vultr Sydney Server

on:
  push:
    branches: [ main, backend/prod ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: []  # 如果要等待 CI 完成，可以添加依赖

    steps:
    - uses: actions/checkout@v4

    - name: Create env file
      run: |
        cp .env.example .env
        cat << EOF >> .env
        EOF

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: ".,!node_modules"
        target: "~/qrent/"

    - name: Deploy application
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/qrent/
          # 使用 printf 来设置环境变量，避免特殊字符问题
          printf -v MYSQL_ROOT_PASSWORD '%s' '${{ secrets.MYSQL_ROOT_PASSWORD }}'
          printf -v EXPOSE_PORT '%s' '3201'
          printf -v DATABASE_URL '%s' 'mysql://root:'"$MYSQL_ROOT_PASSWORD"'@db:3306/qrent'
          printf -v JWT_SECRET '%s' '${{ secrets.JWT_SECRET }}'
          printf -v API_KEY '%s' '${{ secrets.API_KEY }}'
          
          # 导出环境变量
          export MYSQL_ROOT_PASSWORD
          export EXPOSE_PORT
          export DATABASE_URL
          export JWT_SECRET
          export API_KEY
          docker compose down
          docker compose build
          docker compose up -d
          timeout 20 bash -c 'until docker compose ps | grep -q "healthy"; do sleep 2; done'
          
          # Check if the server is responding with status code 200
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3200/echo)
          if [ "$response" != "200" ]; then
            echo "Server health check failed! Got status code: $response"
            exit 1
          else
            echo "Server is up and running with status code 200"
          fi
